---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(leaflet)
```

<main>
<div id="particles-js"></div>

```{r intro}
div(
  style = "height: 100vh;",
  div(
    class = "container section center",
    style = "padding-top: 10vh;",
    id = "home",
    h1(
      class = "brand blue-text link-shadow",
      "Project Vault"
    ),
    h4(
      class = "grey-text text-darken-2",
      "Data, limericks, and other indoor stuff."
    ),
    br(),
    div(
      class = "row",
      div(
        class = "col s4",
        p(
          class = "center-align",
          a(
            href = "https://github.com/JohnCoene",
            target = "_blank",
            class = "btn grey darken-3 waves-effect z-depth-5",
            "GIT"
          )
        )
      ),
      div(
        class = "col s4",
        p(
          class = "center-align",
          a(
            href = "https://www.linkedin.com/in/johncoene/",
            target = "_blank",
            class = "btn blue darken-3 waves-effect z-depth-5",
            "LKN"
          )
        )
      ),
      div(
        class = "col s4",
        p(
          class = "center-align",
          a(
            href = "https://twitter.com/jdatap",
            target = "_blank",
            class = "btn blue lighten-1 waves-effect z-depth-5",
            "TWT"
          )
        )
      )
    )
  )
)
```

```{r parallax 1, eval = FALSE}
div(
  class = "parallax-container hide-on-small-only",
  div(
    class = "parallax",
    img(
      class = "responsive-img",
      src = "img/parallax1.jpg"
    )
  )
)
```

<div id = "nav1" class = "nav1">
```{r}
HTML(
  '
  <nav class="pushpin-nav z-depth-3 hide-on-small-only" data-target="nav1" style="z-index:9999;">
    <div class="nav-wrapper grey lighten-3">
      <div class="container">
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="left hide-on-med-and-down">
          <li><a class="blue-text" href="#web">Web</a></li>
          <li><a class="blue-text" href="#viz">Viz</a></li>
          <li><a class="blue-text" href="#twitter">Twitter</a></li>
          <li><a class="blue-text" href="#data">Data</a></li>
        </ul>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li>
            <a class="dropdown-button blue-text" href="#!" data-activates="social">
              <i class="material-icons right blue-text">arrow_drop_down</i>Connect</a>
              <li><a class="blue-text" href="#contact">Contact</a></li>
          </li>
          <li class ="brand-logo brand blue-text center">
            JOHN COENE
          </li>
        </ul>
      </div>
    </div>
  </nav>
'
)
```

```{r web}
div(
  class = "container section scrollspy",
  id = "web",
  h1(
    class = "blue-text center",
    "Web"
  ),
  div(class = "row",
    h3(
      class = "center orange-text text-lighten-1",
      "five-line"
    ),
    p(
      class = "center grey-text text-darken-2",
      "[ website - App - API - R Package ]"
    )
  ),
  div(
    class = "row",
    div(
      class = "siema z-depth-3",
      div(
        tags$a(
          href = "http://www.five-line.org/",
          target= "_blank",
          img(
            class = "siema-img",
            src = "img/carousels/fiveline_web.png"
          )
        )
      ),
      div(
        tags$a(
          href = "https://play.google.com/store/apps/details?id=org.five_line.www.five_line",
          target= "_blank",
          img(
            class = "siema-img",
            src = "img/carousels/fiveline_app.png"
          )
        )
      ),
      div(
        tags$a(
          href = "http://www.five-line.org/api",
          target= "_blank",
          img(
            class = "siema-img",
            src = "img/carousels/fiveline_api.png"
          )
        )
      ),
      div(
        tags$a(
          href = "https://github.com/JohnCoene/fiveline",
          target= "_blank",
          img(
            class = "siema-img",
            src = "img/carousels/fiveline_package.png"
          )
        )
      )
    ),
    div(
      class = "row",
      br(),
      tags$a(
        class = "prev btn blue lighten-2 left",
        tags$i(
          class = "material-icons",
          "keyboard_arrow_left"
        )
      ),
      tags$a(
        class = "next btn blue lighten-2 right",
        tags$i(
          class = "material-icons",
          "keyboard_arrow_right"
        )
      )
    )
  ),
  div(
    class = "row",
    div(
      class = "col s12 m3",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card sticky-action z-depth-3",
        div(
          class = "card-image",
          img(
            class = "activator",
            src = "img/thumbnails/likealocal.png"
          )
        ),
        div(
          class = "card-content",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "Like a Local",
            tags$i(
              class = "material-icons right",
              "more_vert"
            )
          )
        ),
        div(
          class = "card-action",
          tags$a(
            href="http://www.negotiatelikealocal.com/",
            target = "_blank",
            class = "blue-text link-shadow",
            "Get tips"
          )
        ),
        div(
          class = "card-reveal",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "Negotiate Like a Local",
            tags$i(
              class = "material-icons right",
              "close"
            )
          ),
          p(
            "A Django webapp to explore to get culture-aware negotiation tips based on nationalities.",
            "Ultimately based on the book Negotiate Like a Local and cultural dimensions of Geert Hofstede."
          )
        )
      )
    ),
    div(
      class = "col s12 m3",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card sticky-action z-depth-3",
        div(
          class = "card-image",
          img(
            class = "activator",
            src = "img/thumbnails/wine-dashboard.jpg"
          )
        ),
        div(
          class = "card-content",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "Wine on Twitter",
            tags$i(
              class = "material-icons right",
              "more_vert"
            )
          )
        ),
        div(
          class = "card-action",
          tags$a(
            href="http://johncoene.github.io/wine/",
            target = "_blank",
            class = "blue-text link-shadow",
            "Browse"
          )
        ),
        div(
          class = "card-reveal",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "Wine on Twitter",
            tags$i(
              class = "material-icons right",
              "close"
            )
          ),
          p(
            "A set of of dashboards on wine conversations taking place on Twitter.",
            "Includes dashboards on grape varieties, taste descriptors, wines associated with meal times, and more."
          )
        )
      )
    ),
    div(
      class = "col s12 m3",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card sticky-action z-depth-3",
        div(
          class = "card-image",
          img(
            class = "activator",
            src = "img/thumbnails/marat.png"
          )
        ),
        div(
          class = "card-content",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "Marat",
            tags$i(
              class = "material-icons right",
              "more_vert"
            )
          )
        ),
        div(
          class = "card-action",
          tags$a(
            href="marat",
            class = "blue-text link-shadow",
            "Check it out!"
          )
        ),
        div(
          class = "card-reveal",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "Marat",
            tags$i(
              class = "material-icons right",
              "close"
            )
          ),
          p(
            "A jekyll theme inspired by L'Ami du peuple, an octavo published during the French Revolution ",
            "by Jean-Paul Marat. Ideal for blogging."
          )
        )
      )
    ),
    div(
      class = "col s12 m3",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card sticky-action z-depth-3",
        div(
          class = "card-image",
          img(
            class = "activator",
            src = "img/fullPage3.gif"
          )
        ),
        div(
          class = "card-content",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "fullPage",
            tags$i(
              class = "material-icons right",
              "more_vert"
            )
          )
        ),
        div(
          class = "card-action",
          tags$a(
            href="/packages/fullPage",
            class = "blue-text link-shadow",
            "Explore!"
          )
        ),
        div(
          class = "card-reveal",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "fullPage",
            tags$i(
              class = "material-icons right",
              "close"
            )
          ),
          p(
            "A set of three shiny pages, fullPage.js, pagePiling.js and multiScroll.js to make slick looking Shiny apps."
          )
        )
      )
    )
  )
)
```

```{r viz}
div(
  class = "container section scrollspy",
  id = "viz",
  h1(
    class = "blue-text center",
    "Viz"
  ),
  div(class = "row",
    h3(
      class = "center orange-text text-lighten-1",
      "echarts"
    ),
    p(
      class = "center grey-text text-darken-2",
      "[ Powerful interactive visualizations in R ]"
    )
  ),
  div(
    class = "row",
    div(
      class = "esiema z-depth-3",
      div(
        tags$a(
          href = "htmlwidgets/echarts/",
          img(
            class = "siema-img",
            src = "img/carousels/echarts_types.png"
          )
        )
      ),
      div(
        tags$a(
          href = "htmlwidgets/echarts/",
          img(
            class = "siema-img",
            src = "img/carousels/echarts_themes.png"
          )
        )
      ),
      div(
        tags$a(
          href = "htmlwidgets/echarts/",
          img(
            class = "siema-img",
            src = "img/carousels/echarts_responsive.png"
          )
        )
      )
    ),
    div(
      class = "row hide-on-small-only",
      br(),
      tags$a(
        class = "eprev btn blue lighten-2 left",
        tags$i(
          class = "material-icons",
          "keyboard_arrow_left"
        )
      ),
      tags$a(
        class = "enext btn blue lighten-2 right",
        tags$i(
          class = "material-icons",
          "keyboard_arrow_right"
        )
      )
    )
  ),
  div(
    class = "row",
    div(
      class = "col m4",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card sticky-action z-depth-3",
        div(
          class = "card-image",
          img(
            class = "activator",
            src = "img/thumbnails/peity.png"
          )
        ),
        div(
          class = "card-content",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "peity",
            tags$i(
              class = "material-icons right",
              "more_vert"
            )
          )
        ),
        div(
          class = "card-action",
          tags$a(
            href="https://github.com/JohnCoene/peity",
            target = "_blank",
            class = "blue-text link-shadow",
            "Discover"
          )
        ),
        div(
          class = "card-reveal",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "peity",
            tags$i(
              class = "material-icons right",
              "close"
            )
          ),
          p(
            "peity htmlwidget for R ",
            a(
              href="http://benpickles.github.io/peity/",
              target = "_blank",
              "Peity"
            ),
            ": neat, highly customisable, javascript inline charts in Rmarkdown."
          )
        )
      )
    ),
    div(
      class = "col m4",
      div(
        class = "card sticky-action z-depth-3",
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        div(
          class = "card-image",
          img(
            class = "activator",
            src = "img/thumbnails/chartist.png"
          )
        ),
        div(
          class = "card-content",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "chartist",
            tags$i(
              class = "material-icons right",
              "more_vert"
            )
          )
        ),
        div(
          class = "card-action",
          tags$a(
            href="htmlwidgets/chartist",
            class = "blue-text link-shadow",
            "Start plotting"
          )
        ),
        div(
          class = "card-reveal",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "chartist",
            tags$i(
              class = "material-icons right",
              "close"
            )
          ),
          p(
            "R htmlwidget for chartistjs."
          ),
          tags$ul(
            class = "collection",
            tags$li(
              class = "collection-item",
              "8 chart types"
            ),
            tags$li(
              class = "collection-item",
              "PLenty of plugins"
            ),
            tags$li(
              class = "collection-item",
              "Tons of options"
            ),
            tags$li(
              class = "collection-item",
              "Fully responsive"
            ),
            tags$li(
              class = "collection-item",
              "Animations"
            )
          )
        )
      )
    ),
    div(
      class = "col m4",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card sticky-action z-depth-3",
        div(
          class = "card-image",
          img(
            class = "activator",
            src = "img/thumbnails/uvcharts.png"
          )
        ),
        div(
          class = "card-content",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "uvcharts",
            tags$i(
              class = "material-icons right",
              "more_vert"
            )
          )
        ),
        div(
          class = "card-action",
          tags$a(
            href="htmlwidgets/uvcharts",
            class = "blue-text link-shadow",
            "Start charting"
          )
        ),
        div(
          class = "card-reveal",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "uvcharts",
            tags$i(
              class = "material-icons right",
              "close"
            )
          ),
          p(
            "R htmlwidget for uvcharts.",
            tags$ul(
              class = "collection",
              tags$li(
                class = "collection-item",
                "12 chart types"
              ),
              tags$li(
                class = "collection-item",
                "Palettes"
              ),
              tags$li(
                class = "collection-item",
                "Responsive"
              )
            )
          )
        )
      )
    )
  ),
  div(
    class = "row",
     div(
      class = "col m6",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card sticky-action z-depth-3",
        div(
          class = "card-image",
          img(
            class = "activator",
            src = "img/thumbnails/datamaps.png"
          )
        ),
        div(
          class = "card-content",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "datamaps",
            tags$i(
              class = "material-icons right",
              "more_vert"
            )
          )
        ),
        div(
          class = "card-action",
          tags$a(
            href="datamaps",
            class = "blue-text link-shadow",
            "Start mapping"
          )
        ),
        div(
          class = "card-reveal",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "datamaps",
            tags$i(
              class = "material-icons right",
              "close"
            )
          ),
          p(
            "R htmlwidget for datamaps.",
            tags$ul(
              class = "collection",
              tags$li(
                class = "collection-item",
                "Choropleth"
              ),
              tags$li(
                class = "collection-item",
                "Arcs"
              ),
              tags$li(
                class = "collection-item",
                "Bubbles"
              )
            )
          )
        )
      )
    ),
     div(
      class = "col m6",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card sticky-action z-depth-3",
        div(
          class = "card-image",
          img(
            class = "activator",
            src = "img/thumbnails/billboard.png"
          )
        ),
        div(
          class = "card-content",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "billboard",
            tags$i(
              class = "material-icons right",
              "more_vert"
            )
          )
        ),
        div(
          class = "card-action",
          tags$a(
            href="htmlwidgets/billboard",
            class = "blue-text link-shadow",
            "Start graphing"
          )
        ),
        div(
          class = "card-reveal",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "billboard",
            tags$i(
              class = "material-icons right",
              "close"
            )
          ),
          p(
            "R htmlwidget for billboard.js.",
            tags$ul(
              class = "collection",
              tags$li(
                class = "collection-item",
                "11 chart types"
              ),
              tags$li(
                class = "collection-item",
                "Tons of options"
              ),
              tags$li(
                class = "collection-item",
                "Shiny proxies"
              )
            )
          )
        )
      )
    )
  )
)
```

```{r social media}
div(
  class = "container section scrollspy",
  id = "twitter",
  h1(
    class = "blue-text center",
    "Twitter"
  ),
  div(
    class = "row",
    div(
      class = "col m6",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card sticky-action z-depth-3",
        div(
          class = "card-image",
          img(
            class = "activator",
            src = "img/graphTweets.png"
          )
        ),
        div(
          class = "card-content",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "graphTweets",
            tags$i(
              class = "material-icons right",
              "more_vert"
            )
          )
        ),
        div(
          class = "card-action",
          tags$a(
            href="packages/graphTweets",
            class = "blue-text link-shadow",
            "Visualise"
          )
        ),
        div(
          class = "card-reveal",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "graphTweets",
            tags$i(
              class = "material-icons right",
              "close"
            )
          ),
          p(
            "R package to visualise Twitter interactions. Includes function to write dynamic Gephi file."
          )
        )
      )
    ),
    div(
      class = "col m6",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card sticky-action z-depth-3",
        div(
          class = "card-image",
          img(
            class = "activator",
            src = "img/thumbnails/tweets2earth.png"
          )
        ),
        div(
          class = "card-content",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "tweets2earth",
            tags$i(
              class = "material-icons right",
              "more_vert"
            )
          )
        ),
        div(
          class = "card-action",
          tags$a(
            href="tweets2earth",
            class = "blue-text link-shadow",
            "Get started"
          )
        ),
        div(
          class = "card-reveal",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "tweets2earth",
            tags$i(
              class = "material-icons right",
              "close"
            )
          ),
          p(
            "R package to plot tweets onto Google Earth. Includes function to open generate geo-temporal graph."
          )
        )
      )
    )
  )
)
```

```{r parallax 2, eval = FALSE}
div(
  class = "parallax-container hide-on-small-only",
  div(
    class = "parallax",
    img(
      class = "responsive-img",
      src = "img/parallax2.jpg"
    )
  )
)
```

```{r data}
div(
  class = "container section scrollspy",
  id = "data",
  h1(
    class = "blue-text center",
    "Data"
  ),
  div(class = "row",
    h3(
      class = "center orange-text text-lighten-1",
      "rodham"
    ),
    p(
      class = "center grey-text text-darken-2",
      "[ Download and analyse Hillary Clinton's emails in R ]"
    )
  ),
  div(
    class = "row",
    div(
      class = "rsiema z-depth-3",
      div(
        tags$a(
          href = "packages/rodham/",
          img(
            class = "siema-img",
            src = "img/carousels/rodham_intro.png"
          )
        )
      ),
      div(
        tags$a(
          href = "packages/rodham/",
          img(
            class = "siema-img",
            src = "img/carousels/rodham_releases.png"
          )
        )
      ),
      div(
        tags$a(
          href = "packages/rodham/",
          img(
            class = "siema-img",
            src = "img/carousels/rodham_analyse.png"
          )
        )
      ),
      div(
        tags$a(
          href = "packages/rodham/",
          img(
            class = "siema-img",
            src = "img/carousels/rodham_tidy.png"
          )
        )
      )
    ),
    div(
      class = "row hide-on-small-only",
      br(),
      tags$a(
        class = "rprev btn blue lighten-2 left",
        tags$i(
          class = "material-icons",
          "keyboard_arrow_left"
        )
      ),
      tags$a(
        class = "rnext btn blue lighten-2 right",
        tags$i(
          class = "material-icons",
          "keyboard_arrow_right"
        )
      )
    )
  ),
  div(
    class = "row",
    div(
      class = "col m6",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card sticky-action z-depth-3",
        div(
          class = "card-image",
          img(
            class = "activator",
            src = "img/thumbnails/youTubeDataR.jpg"
          )
        ),
        div(
          class = "card-content",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "youTubeDataR",
            tags$i(
              class = "material-icons right",
              "more_vert"
            )
          )
        ),
        div(
          class = "card-action",
          tags$a(
            href="packages/youTubeDataR/",
            class = "blue-text link-shadow",
            "Get data"
          )
        ),
        div(
          class = "card-reveal",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "youTubeDataR",
            tags$i(
              class = "material-icons right",
              "close"
            )
          ),
          p(
            "youTubeDataR is an R package that wraps the YouTube Data API, features all ", 
            code("GET"), 
            " functions."
          )
        )
      )
    ),
    div(
      class = "col m6",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card sticky-action z-depth-3",
        div(
          class = "card-image",
          img(
            class = "activator",
            src = "img/thumbnails/bibler.jpg"
          )
        ),
        div(
          class = "card-content",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "bibler",
            tags$i(
              class = "material-icons right",
              "more_vert"
            )
          )
        ),
        div(
          class = "card-action",
          tags$a(
            href="packages/bibler",
            class = "blue-text link-shadow",
            "Explore"
          )
        ),
        div(
          class = "card-reveal",
          tags$span(
            class = "card-title activator grey-text text-darken-2", 
            "bibler",
            tags$i(
              class = "material-icons right",
              "close"
            )
          ),
          p(
            "R package that includes all the Bible books (King James version) ",
            "and some text mining utilities to deal with Middle English."
          )
        )
      )
    )
  )
)
```

```{r misc}
div(
  class = "container section",
  id = "misc",
  h1(
    class = "blue-text center",
    "Misc"
  ),
  div(
    class = "row",
    tags$ul(
      class = "collapsible popout",
      `data-collapsible` = "accordion",
      tags$li(
        div(
          class = "collapsible-header blue-text",
          tags$i(
            class = "material-icons",
            "text_format"
          ),
          "typed"
        ),
        div(
          class = "collapsible-body",
          tags$span(
            "typed is an R implementation of ",
            a(
              href = "https://github.com/mattboldt/typed.js",
              "typed.js"
            ),
            ".",
            tags$a(
              href = "https://github.com/JohnCoene/typed",
              target = "_blank",
              class = "right link-shadow",
              "Start typing"
            )
          )
        )
      ),
      tags$li(
        div(
          class = "collapsible-header active blue-text",
          tags$i(
            class = "material-icons",
            "insert_drive_file"
          ),
          "reporter"
        ),
        div(
          class = "collapsible-body",
          tags$span(
            "Rmarkdown format; implementation of fullpage.js and materialize CSS (WIP)."
          ),
            tags$a(
              href = "reporter",
              class = "right link-shadow",
              "Start reporting"
            )
        )
      ),
      tags$li(
        div(
          class = "collapsible-header blue-text",
          tags$i(
            class = "material-icons",
            "alarm"
          ),
          "countup"
        ),
        div(
          class = "collapsible-body",
          tags$span(
            "R implementation of ",
            a(
              href = "https://inorganik.github.io/countUp.js/",
              "countup.js"
            ),
            ".",
            tags$a(
              href = "countup",
              class = "right link-shadow",
              "Get counting"
            )
          )
        )
      ),
      tags$li(
        div(
          class = "collapsible-header blue-text",
          tags$i(
            class = "material-icons",
            "filter_drama"
          ),
          "egg"
        ),
        div(
          class = "collapsible-body",
          tags$span(
            "R package to put easter eggs in your Rmarkdown reports; text and images."
          ),
            tags$a(
              href = "egg",
              class = "right link-shadow",
              "Get cooking"
            )
        )
      )
    )
  )
)
```

```{r contact}
map <- leaflet() %>% 
  addTiles() %>% 
  addMarkers(lat = 46.204391, 
             lng = 6.143158,
             popup="John")

div(
  class = "section",
  id = "contact",
  h1(
    class = "blue-text center",
    "Contact"
  ),
  p(
    class = "grey-text text-darken-1 center",
    "Feedback is most welcome."
  ),
  div(
    class = "row",
    tags$form(
      action = "https://formspree.io/jcoenep@gmail.com",
      method = "POST",
      class = "col s12",
      div(
        class = "row",
        div(
          class = "input-field col m3 s6 push-m3",
          tags$i(
            class = "material-icons prefix",
            "account_circle"
          ),
          tags$input(
            placeholder="Your name",
            id = "name_prefix",
            type = "text",
            name = "name",
            class = "validate"
          ),
          tags$label(
            `for` = "name_prefix",
            "Name"
          )
        ),
        div(
          class = "input-field col m3 s6 push-m3",
          tags$i(
            class = "material-icons prefix",
            "mail_outline"
          ),
          tags$input(
            placeholder="Your email",
            id = "mail_prefix",
            type = "text",
            name = "_replyto",
            class = "validate"
          ),
          tags$label(
            `for` = "mail_prefix",
            "Email"
          )
        )
      ),
      div(
        class = "row",
        div(
          class = "input-field col m6 s12 push-m3",
          tags$i(
            class = "material-icons prefix",
            "edit"
          ),
          tags$textarea(
            placeholder="Your message",
            id = "message_prefix",
            name="message",
            `data-length` = "500",
            class = "materialize-textarea validate"
          ),
          tags$label(
            `for` = "message_prefix",
            "Message"
          ) 
        )
      ),
      div(
        class = "row",
        div(
          class = "col s4 push-m4 push-s4 center",
          tags$input(
            type = "submit",
            value = "Send",
            class ="blue btn waves-effect waves-light"
          )
        )
      )
    )
  ),
  map
)
```

</div>
</main>