---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<main>
<div class = "container">

### What is it?

John Coene is a freelance social media data analyst. If you land on this page it must that you requested my services to analyse Instagram data relevant to you.

* Full Legal Name: Jean-Philippe Coene known as "John"
* Emails addresses: jcoenep@hotmail.com | jcoenep@gmail.com
* Website: [john-coene.com](http://john-coene.com/)

### Compliance

I fully comply with Instagram's [terms](https://www.instagram.com/about/legal/terms/api/).

### Remove Access

You can revoke access to this app at any time which mean I will not be able to collect your data any longer.

1. From your computer, go to the Instagram website. Log in with your username and password.
2. From the homepage at the top-right corner of the screen, you will find your Instagram username. Click your username and from the drop-down menu, select ‘Edit Profile’. When it is clicked, a new page will open that has a list of choices on the left corner.
3. Select the ‘Manage Application’ button from the list.
4. Click the ‘Revoke Access’ for the app that you want to disconnect to your Instagram account. After that, a dialog box will open to confirm about revoking the access.
5. Click ‘Yes’ to revoke access.

### Storage

Your data is **NOT stored**.

I only work with interactive HTML documents that dynamically query the api and visualise the data. Your data will not be saved anywhere!

### Permissions

Below I detail why I require each of the permissions. Note that I only perform **GET queries** and that therefore I do not **POST** or **DELETE** any of your content; I can only **GET** data.

#### basic

This permission lets me collect profile information and media.

This in essence allows me see your personal details and information, it forms the backbone of the analysis.

#### follower_list

This allows me to collect the list of your followers as well as the list of accounts you follow.

This is crucial for me to analyse your follower base, their interests, as well as yours.

#### public_content

This allows me to read all public content you share. 

This is quite essential to any analysis I run; I need to be able to collect your posts and their respective performance in order to compute metrics including but not limited to "engagement."

</div>
</main>