---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<main>

```{r}
div(
  class = "section container",
  h2(
    class = "center grey-text text-darken-2",
    "Marat"
  ),
  img(
    src = "https://raw.githubusercontent.com/JohnCoene/marat/master/assets/img/screenshot.png",
    class = "responsive-img z-depth-2"
  ),
  br(),
  h4(
    class = "grey-text text-darken-2",
    "Revice the values of the Enlightenment with marat!"
  ),
  br(),
  a(
    target = "_blank",
    href = "https://github.com/JohnCoene/marat",
    class = "btn waves-effect center blue",
    tags$i(
      class = "material-icons left",
      "code"
    ),
    "Repository"
  ),
  a(
    target = "_blank",
    href = "http://johncoene.github.io/marat",
    class = "btn waves-effect center blue lighten-1",
    tags$i(
      class = "material-icons left",
      "devices"
    ),
    "Demo"
  ),
  a(
    target = "_blank",
    href = "https://github.com/JohnCoene/marat/archive/master.zip",
    class = "btn waves-effect center blue lighten-2",
    tags$i(
      class = "material-icons left",
      "file_download"
    ),
    "Download"
  ),
  div(
    class = "row",
    p(
      "Marat is heavily inspired by ",
      a(
        "L'Ami du peuple",
        href = "https://en.wikipedia.org/wiki/L%27Ami_du_peuple",
        target = "_blank"
      ),
      ", a newspaper written by ",
      a(
        "Jean Paul Marat",
        href = "https://en.wikipedia.org/wiki/Jean-Paul_Marat",
        target = "_blank"
      ),
      "during the French Revolution, in which he was vocal advocate for the rights of man and liberty."
    )
  ),
  div(
    class = "row",
    tags$ol(
      tags$li(
        "Adapt the ", 
        tags$code("_config.yml"),
        "file."
      ),
      tags$li(
        "Replace/Delete the posts."
      ),
      tags$li(
        "Change", 
        tags$code("about.md")
      ),
      tags$li(
        "Change or add your links in the ", 
        tags$code("nav.yml"),
        "file located in the ",
        tags$code("_data"),
        "folder."
      ),
      tags$li(
        "Enlighten the masses"
      )
    ),
    pre(
      code(
        "devtools::install_github('stuff')"
      )
    )
  )
)
```

</main>