---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(uvcharts)
```

<main>
<div class="container">

```{r, echo=FALSE}
h1(
  "Chart types"
)
```

```{r}
# create data
df <- data.frame(x = 1:10, y = runif(10, 0, 5), z = runif(10, 0, 5))
```

### Bar

```{r}
df %>%
  uv_bar(x) %>%
  uv_add(y) %>%
  uv_add(z) %>%
  uv_frame(bgcolor = "none")
```

### Stacked bar

```{r}
df %>%
  uv_stackbar(x) %>%
  uv_add(y) %>%
  uv_add(z) %>%
  uv_frame(bgcolor = "none")
```

### Percent bar

```{r}
df %>%
  uv_percentbar(x) %>%
  uv_add(y) %>%
  uv_add(z) %>%
  uv_frame(bgcolor = "none")
```

### Stepup bar

```{r}
df %>%
  uv_stepupbar(x) %>%
  uv_add(y) %>%
  uv_add(z) %>%
  uv_frame(bgcolor = "none")
```

### Line

```{r}
df %>%
  uv_line(x) %>%
  uv_add(y) %>%
  uv_add(z) %>%
  uv_graph(orientation = "Vertical") %>%
  uv_frame(bgcolor = "none")
```

### Area

```{r}
df %>%
  uv_area(x) %>%
  uv_add(y) %>%
  uv_add(z) %>%
  uv_graph(orientation = "Vertical") %>%
  uv_frame(bgcolor = "none")
```

### Stacked area

```{r}
df %>%
  uv_stackarea(x) %>%
  uv_add(y) %>%
  uv_add(z) %>%
  uv_graph(orientation = "Vertical") %>%
  uv_frame(bgcolor = "none")
```

### Percent area

```{r}
df %>%
  uv_percentarea(x) %>%
  uv_add(y) %>%
  uv_add(z) %>%
  uv_graph(orientation = "Vertical") %>%
  uv_frame(bgcolor = "none")
```

### Pie

```{r}
df <- data.frame(x = c("apple", "banana", "cake", "mango", "strawberry"), y = c(1,4,2,5,3))
```

```{r}
df %>%
  uv_pie(x) %>%
  uv_add(y) %>%
  uv_frame(bgcolor = "none")
```

### Polar

```{r}
df %>%
  uv_polar(x) %>%
  uv_add(y) %>%
  uv_frame(bgcolor = "none")
```

### Waterfall

```{r}
df %>%
  uv_waterfall(x) %>%
  uv_add(y) %>%
  uv_frame(bgcolor = "none")
```

### Any

Pass any charts with `uv_chart` specifying `type` (CamelCase).

```{r}
df %>%
  uv_charts(x, type = "Bar") %>%
  uv_add(y) %>%
  uv_frame(bgcolor = "none")
```

</div>
</main>