---
title: "Chord graph examples"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Basic Chord

This is a reproduction of the following [example](http://echarts.baidu.com/echarts2/doc/example/chord1.html#-en) taken from Baidu's EChart official website.

```{r}
matrix <- matrix(sample(0:1, 100, replace = TRUE, prob = c(0.9,0.6)), nc = 10)

matrix %>% 
  echart(LETTERS[1:10]) %>% 
  echord() %>% 
  etitle("Test data", subtext = "'From d3.js", x = "right", y = "bottom") %>% 
  etoolbox_magic(type = list("force", "chord"))
```

## Ribbon Chord

This is a reproduction of the following [example](http://echarts.baidu.com/echarts2/doc/example/chord4.html#-en) taken from Baidu's EChart official website.

```{r}
matrix <- matrix(sample(0:1, 100, replace = TRUE, prob = c(0.9,0.6)), nc = 10)

matrix %>% 
  echart(LETTERS[1:10]) %>% 
  echord(ribbonType = FALSE) %>% 
  etitle("German team effectiveness alliance", x = "right", y = "bottom") %>% 
  etoolbox_magic(type = list("force", "chord"))
```
