---
title: "Combinations"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(echarts)
```

## line, pie & bar

Reproduction of the following [example](http://echarts.baidu.com/echarts2/doc/example/mix2.html#-en) on the official website.

```{r}
pie <- data.frame(name = c("MKTG", "MGMT", "BD"), values = c(5, 8, 3))

df <- data.frame(day = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"),
                 direct = c(320, 332, 301, 334, 390, 330, 320),
                 mail = c(120, 132, 101, 134, 90, 230, 210),
                 affiliate = c(220, 182, 191, 234, 290, 330, 310),
                 video = c(150, 232, 201, 154, 190, 330, 410),
                 search = c(862, 1018, 964, 1026, 1679, 1600, 1570))

pie %>% 
  echart(name, width = "100%") %>% 
  epie(values, center = list(160,130), radius = list(0, 50)) %>% 
  edata(df, day) %>%
  ebar(direct, stack = "grp1") %>% 
  ebar(mail, stack = "grp2") %>% 
  ebar(affiliate, stack = "grp2") %>% 
  ebar(video, stack = "grp2") %>% 
  eline(search) %>% 
  exAxis(type = "category") %>% 
  eyAxis(type = "value", position = "right") %>% 
  etheme("macarons")
```

## Line & bar

Reproduction of the following [example](http://echarts.baidu.com/echarts2/doc/example/mix6.html#-en) on the official website.

```{r}
df <- data.frame(day = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"),
                 topLine = c(400, 374, 251, 300, 420, 400, 440),
                 bottomLine = c(320, 332, 301, 334, 360, 330, 350),
                 bottomBar = c(320, 332, 251, 300, 360, 330, 350),
                 bar = c(80, 42, 50, 34, 60, 70, 90))

hide_line <- list(normal = list(color = "rgba(0,0,0,0)"), 
                  emphasis = list(color = "rgba(0,0,0,0)"))

df %>% 
  echart(day, width = "100%") %>% 
  eline(topLine, showAllSymbols = TRUE, symbol = "emptyCircle", symbolSize = 5) %>% 
  eline(bottomLine) %>% 
  ebar(bottomBar, itemStyle = hide_line, stack = "grp", barWidth = 6) %>% 
  ebar(bar, stack = "grp") %>% 
  etheme("macarons")
```

## Funnel & Gauge

Reproduction of the following [example](http://echarts.baidu.com/echarts2/doc/example/mix11.html#-en) on the official website.

```{r}
expected <- data.frame(values = c(60, 40, 20, 80, 100),
                       names = c("Access", "Advice", "Order", "Click", "Print"))

actual <- data.frame(values = c(30, 10, 5, 50, 80),
                     names = c("Access", "Advice", "Order", "Click", "Print"))

expected %>% 
  echart(names, width = "100%") %>% 
  efunnel(values, x = "45%", width = "45%", itemStyle = list(normal = list(labelLine = list(show = FALSE)))) %>% 
  edata(actual, names) %>% 
  efunnel(values, x = "45%", width = "45%", maxSize = "80%",
          itemStyle = list(normal = list(borderColor = "#FFF", borderWidth = 2,
                                         label = list(position = "inside", formatter = "{c}%", 
                                                      textStyle = list(color = "#FFF"))))) %>% 
  egauge(50, "Indicator", center = list("25%", "55%"))
```