---
title: "Gauges"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(echarts)
```

## Basic

This is a reproduction of the following [example](http://echarts.baidu.com/echarts2/doc/example/gauge1.html#-en) taken from Baidu's EChart official website.

```{r}
echart(width = "100%") %>%
  egauge(85, "Completion rate") %>% 
  etoolbox_full() %>% 
  etooltip(trigger = "item") %>% 
  etheme("macarons")
```

## Dark

This is a reproduction of the following [example](http://echarts.baidu.com/echarts2/doc/example/gauge3.html#-en) taken from Baidu's EChart official website.

```{r}
axis_label <- htmlwidgets::JS("
function(v){
  switch (v+''){
    case '10': return 'low';
    case '50': return 'Medium';
    case '90': return 'High';
    default: return '';}}")

text <- list(color = "#FFF")

echart(width = "100%") %>%
  egauge(85, "Completion rate", axisLabel = list(formatter = axis_label, textStyle = text)) %>% 
  etooltip(trigger = "item") %>%
  etoolbox_full() %>% 
  etheme("dark")
```