---
title: "echarts"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(echarts)
library(htmltools)
air <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv')
flights <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/2011_february_aa_flight_paths.csv')

# split large airports and smaller one
large_airports <- air[air$cnt > quantile(air$cnt, 0.95), ]
small_airports <- dplyr::anti_join(air, large_airports, by = "iata")

# split freuqent and less frequent flights
frequent <- flights[flights$cnt > quantile(flights$cnt, 0.95), ]
sparse <- flights[flights$cnt < quantile(flights$cnt, 0.95),]
```

```{r header}
# customise line effect
line.effect <- list(loop = TRUE,
                    show = TRUE,
                    scaleSize = 2,
                    period = 40,
                    shadowBlur = 5)

point.effect <- list(show = TRUE, shadowBlur = 10)
item.style <- list(normal = list(lineStyle = list(type = "dotted", shadowBlur = 2)))

large_airports %>% 
  echart(iata, width = "100%") %>% 
  emap(mapType = "world|United States of America") %>% 
  emap_coords(long, lat) %>% 
  emap_points(cnt, symbol = "emptyCircle", effect = point.effect) %>% 
  emap_lines(frequent, airport1, airport2, effect = line.effect) %>% 
  edata(small_airports, iata) %>% 
  emap(mapType = "world|United States of America") %>% 
  emap_coords(long, lat) %>% 
  emap_points(cnt, symbol = "circle", symbolSize = 2) %>% 
  emap_lines(sparse, airport1, airport2, itemStyle = item.style) %>% 
  etooltip() %>% 
  etheme("infographic")
```

```{r chart types}
div(class = "page-header",
    h2("Features", class = "text-primary"))
```

1. bar charts
2. line charts
3. area charts
4. pie & donut charts
5. heatmaps
6. chord diagrams
7. venn diagrams
8. gauges
9. force networks
10. word-clouds
11. maps
12. themes
13. responsive
14. animations

```{r install}
div(class = "page-header",
    h2("Install", class = "text-primary"))
```

```{r install code, eval=FALSE, echo=TRUE}
devtools::install_github("JohnCoene/echarts")
```

```{r Explanation}
div(class = "page-header",
    h2("How it works?", class = "text-primary"))
```

**EASY**

Initialise your chart with `echart` then add series, supports magrittr pipes, `%>%`, supports `dplyr`'s `group_by`.

```{r first chart}
div(class = "page-header",
    h2("Your first chart", class = "text-primary"))
```

```{r first chart code, eval=TRUE, echo=TRUE}
df <- data.frame(x = 1:20,
                 y = round(runif(20, 5, 10)),
                 z = round(runif(20, 7, 12)),
                 w = round(runif(20, 9, 14)))

df %>% 
  echart(x, width = "100%") %>% 
  ebar(y) %>% 
  eline(z) %>%
  escatter(w) %>%
  etooltip(trigger = "axis")
```

```{r advanced}
div(class = "page-header",
    h2("Advanced Example", class = "text-primary"))
```

Code used to make map in header.

```{r adv, echo=TRUE, eval = FALSE}
# download data
air <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv')
flights <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/2011_february_aa_flight_paths.csv')

# split large airports and smaller one
large_airports <- air[air$cnt > quantile(air$cnt, 0.95), ]
small_airports <- dplyr::anti_join(air, large_airports, by = "iata")

# split frequent and less frequent flights
frequent <- flights[flights$cnt > quantile(flights$cnt, 0.95), ]
sparse <- flights[flights$cnt < quantile(flights$cnt, 0.95),]

# customise line effect
line.effect <- list(loop = TRUE,
                    show = TRUE,
                    scaleSize = 2,
                    period = 40,
                    shadowBlur = 5)

point.effect <- list(show = TRUE, shadowBlur = 10)
item.style <- list(normal = list(lineStyle = list(type = "dotted", shadowBlur = 2)))

large_airports %>% 
  echart(iata, width = "100%") %>% 
  emap(mapType = "world|United States of America") %>% 
  emap_coords(long, lat) %>% 
  emap_points(cnt, symbol = "emptyCircle", effect = point.effect) %>% 
  emap_lines(frequent, airport1, airport2, effect = line.effect) %>% 
  edata(small_airports, iata) %>% 
  emap(mapType = "world|United States of America") %>% 
  emap_coords(long, lat) %>% 
  emap_points(cnt, symbol = "circle", symbolSize = 2) %>% 
  emap_lines(sparse, airport1, airport2, itemStyle = item.style) %>% 
  etooltip() %>% 
  etheme("infographic")
```