---
title: "Network examples"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(echarts)
library(dplyr)
```

## Simple topology

This is a reproduction of the following [example](http://echarts.baidu.com/echarts2/doc/example/force1.html#-en) taken from Baidu's EChart official website.

```{r simp}
set.seed(19882505)
grps <- LETTERS[1:4]

nodes <- data.frame(name = LETTERS[1:20],
                    value = round(runif(20, 5, 25)),
                    grps = sample(grps, 20, replace = T))

edges <- data.frame(from = sample(LETTERS[1:20], 30, replace = TRUE),
                    to = sample(LETTERS[1:20], 30, replace = TRUE))

showLabel <- list(normal = list(label = list(show = TRUE)))

echart(width = "100%") %>% 
  eforce(itemStyle = showLabel) %>% 
  enodes(nodes, name = name, label = name, value = value, category = grps) %>% 
  elinks(edges, from, to) %>% 
  elegend(orient = "horizontal")
```

## Larger

Using datasets from [plotly](https://plot.ly/r/lines-on-maps/):

* [airports](https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv')
* [flights](https://raw.githubusercontent.com/plotly/datasets/master/2011_february_aa_flight_paths.csv)

The datasets above are downloaded from R:

```{r dl}
air <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv')
flights <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/2011_february_aa_flight_paths.csv')
```

```{r adv}
echart(width = "100%") %>% 
  eforce(maxRadius = 8, minRadius = 3, gravity = 0.8, large = TRUE) %>% 
  enodes(air, iata, airport, cnt) %>% 
  elinks(flights, airport1, airport2) %>% 
  etooltip(trigger = "item") %>% 
  etheme("macarons2")
```