---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(echarts)
```

<main>
<div class = "container">

```{r, echo=FALSE}
h1(
  "Radar charts"
)
```

### Basic

[example](http://echarts.baidu.com/echarts2/doc/example/radar1.html#-en)

```{r}
axis <- c("sales", "marketing", "development", "customer support", "IT", "admin")
radar <- data.frame(axis = rep(axis, 2),
                    values = runif(12, 2, 10),
                    groups = c(rep("grp1", 6), rep("grp2", 6)))

radar %>% 
  group_by(groups) %>% 
  echart(axis, width = "100%") %>% 
  eradar(values) %>% 
  elegend() %>% 
  etooltip(trigger = "axis") %>% 
  etoolbox_full() %>% 
  etheme("macarons")
```

### Filled

[example](http://echarts.baidu.com/echarts2/doc/example/radar2.html#-en)

```{r}
axis <- c("sales", "marketing", "development", "customer support", "IT", "admin")
radar <- data.frame(axis = rep(axis, 2),
                    values = runif(12, 2, 10),
                    groups = c(rep("grp1", 6), rep("grp2", 6)))

fill <- list(normal = list(areaStyle = list(type = "default")))

radar %>% 
  group_by(groups) %>% 
  echart(axis, width = "100%") %>% 
  eradar(values, itemStyle = fill, symbolSize = 0) %>% 
  elegend() %>% 
  etoolbox_full()
```

</div>
</main>