---
title: "Scatter chart examples"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(echarts)
```

## Mark points

This is a reproduction of the following [example](http://echarts.baidu.com/echarts2/doc/example/scatter1.html#-en) taken from Baidu's EChart official website.

```{r}
df <- data.frame(x = 1:150,
                 y = round(rnorm(150, mean = 5, sd = 1), 2),
                 z = round(rnorm(150, mean = 7, sd = 1), 2))

pointer <- list(
  show = TRUE,
  type = "cross",
  lineStyle = list(
    type = "dashed",
    width = 0.8
  )
)

df %>% 
  echart(x) %>% 
  escatter(y) %>% 
  escatter(z) %>% 
  emark_point(which = "all", data = list(list(type = "min"), list(type = "max"))) %>% 
  emark_line(which = "all", data = list(list(type = "average"))) %>% 
  etheme("macarons") %>% 
  elegend() %>% 
  etoolbox_full() %>% 
  etooltip(axisPointer = pointer, showDelay = 0)
```

## Bubble

This is a reproduction of the following [example](http://echarts.baidu.com/echarts2/doc/example/scatter2.html#-en) taken from Baidu's EChart official website.

```{r}
df <- data.frame(x = 1:150,
                 y = round(rnorm(150, mean = 5, sd = 1), 2),
                 z = runif(150, 10, 50))

df %>% 
  echart(x) %>% 
  escatter(y, z, name = "scatter 1", symbolSize = 10) %>%
  elegend() %>% 
  etoolbox_full() %>% 
  etoolbox_zoom() %>% 
  exAxis(type = "value") %>% 
  etoolbox_full()
```


## Scale

This is a reproduction of the following [example](http://echarts.baidu.com/echarts2/doc/example/dataRange1.html#-en) taken from Baidu's EChart official website.

```{r}
df <- data.frame(x = 1:500, y = runif(500, 1, 20), z = round(runif(500, 0, 10)))

df %>% 
  echart(x) %>% 
  escatter(y, z, symbolSize = 10) %>% 
  ecolorbar(calculable = FALSE, 
            color = list('lightgreen','yellow'), 
            min = 0, 
            max = 10, 
            splitNumber = 5,
            x = "left",
            y = "top",
            orient = "horizontal") %>% 
  exAxis(type = "value") %>% 
  etooltip(axisPointer = list(show = TRUE), trigger = "item") %>% 
  etoolbox_full()
```