---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(htmltools)
library(leaflet)
library(dplyr)
library(egg)
```

<main>
<div class = "container">

```{r}
egg(c("c", "o", "e", "n", "e"), imegg = "img/jp.png", timeout = 10000) # easter egg

div(
  style = "height: 90vh; margin-top: 10vh;",
  class = "section scrollspy",
  id = "home",
  div(
    h1(
      class = "red-text center text-lighten-1",
      tags$span(
        class = "brand",
        "John-seeks-a-job"
      ),
      br(),
      tags$span(
        class = "norm grey-text text-darken-1",
        "Europe tour"
      )
    ),
    p(
      class = "italics center grey-text hide-on-small-only",
      "Starts in"
    ),
    div(
      class = "hide-on-small-only",
      style="text-align: center;",
      div(
        style="display: inline-block; width: auto;",
        class = "your-clock"
      )
    )
  ),
  br(),
  br(),
  br(),
  br(),
  div(
    class = "center",
    tags$a(
      href = "#book",
      class = "btn pulse teal waves-effect waves-light",
      tags$i(
        class = "material-icons left",
        "receipt"
      ),
      "BOOK NOW!"
    ),
    p(
      br(),
      br(),
      class = "grey-text hide-on-small-only italics",
      "Type 'Coene' to see John!"
    )
  )
)
```

```{r where is john}
div(
  class = "row center",
  style = "min-height: 300px;",
  h2(
    class = "teal-text",
    "Where is John right now?"
  ),
  h5(
    "Right now John is in ",
    span(
      class = "red-text text-lighten-1 link-shadow",
      id = "place"
    ),
    "!"
  )
)
```

```{r}
div(
  class = "section scrollspy",
  id = "about",
  div(
    class = "row",
    div(
      class = "col m12 center",
      tags$img(
        src = "img/jp.png",
        class = "responsive-img circle",
        style = "max-height:70px;"
      ),
      h3(
        class = "teal-text",
        '"Data Guy"'
      ),
      p(
        "5 years of progressive experience in the realm of analytics ranging from data collection to visualisation through analysis."
      ),
      p(
        span(
          class = "red-text text-lighten-1",
          "Languages:"
        ),
        "English & French."
      ),
      p(
        span(
          class = "red-text text-lighten-1",
          "Domain knowledge:"
        ),
        "Social Media Analysis, web analytics, mobile analytics and market research."
      ),
      p(
        span(
          class = "red-text text-lighten-1",
          "Technical skills:"
        ),
        "R, Rmarkdown, Shiny, Django, Git, SQL (PostgreSQL, SQLite, MySQL), web stuff (HTML, CSS, javascript), and plenty more."
      ),
      p(
        tags$a(
          class = "btn red lighten-1",
          href = "http://john-coene.com",
          target = "_blank",
          tags$i(
            class = "material-icons left",
            "bubble_chart"
          ),
          "Portfolio"
        ),
        tags$a(
          class = "btn teal lighten-1",
          href = "http://johncoene.github.io/cv",
          target = "_blank",
          tags$i(
            class = "material-icons right",
            "person"
          ),
          "Resume"
        )
      )
    )
  )
)
```

```{r tabs, eval=FALSE}
div(
  class = "section scrollspy",
  id = "about",
  tags$ul(
    id = "tabs",
    class ="tabs",
    tags$li(
      class = "tab col s6 left",
      tags$a(
        href = "#tab1",
        "WHAT"
      )
    ),
    tags$li(
      class = "tab col s6 right",
      tags$a(
        href = "#tab2",
        "WHO"
      )
    )
  ),
  div(
    style = "min-height: 300px;",
    id = "tab1",
    class = "col s12",
    div(
      class = "row",
      p(
        class = "center",
        "John is a Belgian citizen who seeks to return to Europe after living and working 5 years in China.",
        br(),
        "He has organised this tour so that we get to meet.",
        tags$i(
          class = "material-icons",
          "local_cafe"
        )
      ),
      h2(
        class = "red-text text-lighten-1 center",
        "Let's chat!"
      )
    )
  ),
  div(
    style = "min-height: 300px;",
    id = "tab2",
    class = "col s12",
    div(
      class = "row",
      div(
        class = "col m4",
        tags$img(
          src = "img/jp.png",
          class = "responsive-img"
        )
      ),
      div(
        class = "col m8",
        h5(
          class = "teal-text",
          "Data person"
        ),
        p(
          "5 years of progressive experience in data ranging from data collection to visualisation through analysis."
        ),
        p(
          tags$span(
            class = "red-text text-lighten-2",
            "Domain knowledge:"
          ),
          "Social Media Analysis (text mining, social network analysis), web analytics, mobile analytics and market research."
        ),
        p(
          tags$span(
            class = "red-text text-lighten-2",
            "Technical:"
          ),
          "R, Shiny, Rmarkdown, Shiny, Django, Git, SQL (PostgreSQL, SQLite, MySQL), web stuff (HTML, CSS, javascript), and plenty more."
        ),
        p(
          tags$span(
            class = "red-text text-lighten-2",
            "Languages:"
          ),
          "English & French."
        ),
        p(
          tags$a(
            class = "btn red lighten-1",
            href = "http://john-coene.com",
            target = "_blank",
            tags$i(
              class = "material-icons left",
              "blur_on"
            ),
            "Portfolio"
          ),
          tags$a(
            class = "btn red lighten-2",
            href = "http://johncoene.github.io/cv",
            target = "_blank",
            tags$i(
              class = "material-icons right",
              "person"
            ),
            "Resume"
          )
        )
      )
    )
  )
)
```

```{r map}
tour <- read.csv("data/tour.csv")

# time
tour$date_diff <- as.Date(as.character(tour$To), format="%d/%m/%Y") -
                  as.Date(as.character(tour$From), format="%d/%m/%Y")

# tooltip
tour <- tour %>% 
  mutate(tooltip = paste0(date_diff, " days in ", "<span style='color:#009688;'>", City, "</span><br>",
                          From, ": ", To))

icons <- awesomeIcons(
  icon = 'coffee',
  iconColor = '#eeeeee',
  library = 'ion',
  markerColor =  "#009688"
)

p <- tour %>% 
  leaflet(
        width = "100%",
        height = "400px") %>% 
  addTiles() %>%
  addAwesomeMarkers(~long, ~lat, icon=icons, label=~as.character(City), 
                    popup = ~tooltip) %>% 
  addProviderTiles(providers$CartoDB.Positron)
```


```{r}
div(
  class = "row section scrollspy",
  id = "dates",
  h2(
      class = "teal-text center",
      "TOUR"
    ),
  div(
    class = "col m12 s12",
    p
  )
)
```

```{r locations}
div(
  class = "section scrollspy",
  id = "locations",
  h2(
      class = "teal-text center",
      "DATES"
  ),
  div(
    class = "row",
    div(
      class = "col s12 m4",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card",
        div(
          class = "card-image",
          tags$img(
            src = "img/london.png"
          ),
          tags$span(
            class = "card-title",
            "LONDON"
          )
        ),
        div(
          class = "card-content",
          tags$p(
            "John can be in London between the 21/09/2017 and the 25/09/2017."
          )
        ),
        div(
          class = "card-action",
          tags$a(
            class = "red-text text-lighten-1",
            href = "#book",
            "BOOK NOW!"
          )
        )
      )
    ),
    div(
      class = "col s12 m4",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card",
        div(
          class = "card-image",
          tags$img(
            src = "img/brussels.png"
          ),
          tags$span(
            class = "card-title",
            "Brussels"
          )
        ),
        div(
          class = "card-content",
          tags$p(
            "John will be in Brussels between the 25/09/2017 and the 26/09/2017."
          )
        ),
        div(
          class = "card-action",
          tags$a(
            class = "red-text text-lighten-1",
            href = "#book",
            "BOOK NOW!"
          )
        )
      )
    ),
    div(
      class = "col s12 m4",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card",
        div(
          class = "card-image",
          tags$img(
            src = "img/bern.png"
          ),
          tags$span(
            class = "card-title",
            "Bern"
          )
        ),
        div(
          class = "card-content",
          tags$p(
            "John can be in Bern between the 30/08/2017 and the 01/09/2017."
          )
        ),
        div(
          class = "card-action",
          tags$a(
            class = "red-text text-lighten-1",
            href = "#book",
            "BOOK NOW!"
          )
        )
      )
    )
  ),
  div(
    class = "row",
    div(
      class = "col s12 m4",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card",
        div(
          class = "card-image",
          tags$img(
            src = "img/milan.png"
          ),
          tags$span(
            class = "card-title",
            "Milan"
          )
        ),
        div(
          class = "card-content",
          tags$p(
            "John is in Milan between the 01/09/2017 and the 06/09/2017."
          )
        ),
        div(
          class = "card-action",
          tags$a(
            class = "red-text text-lighten-1",
            href = "#book",
            "BOOK NOW!"
          )
        )
      )
    ),
    div(
      class = "col s12 m4",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card",
        div(
          class = "card-image",
          tags$img(
            src = "img/pisa.png"
          ),
          tags$span(
            class = "card-title",
            "Pisa"
          )
        ),
        div(
          class = "card-content",
          tags$p(
            "John is in Pisa between the 06/09/2017 and the 11/09/2017."
          )
        ),
        div(
          class = "card-action",
          tags$a(
            class = "red-text text-lighten-1",
            href = "#book",
            "BOOK NOW!"
          )
        )
      )
    ),
    div(
      class = "col s12 m4",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card",
        div(
          class = "card-image",
          tags$img(
            src = "img/marseille.png"
          ),
          tags$span(
            class = "card-title",
            "Marseille"
          )
        ),
        div(
          class = "card-content",
          tags$p(
            "John is in Marseile between the 11/09/2017 and the 12/09/2017."
          )
        ),
        div(
          class = "card-action",
          tags$a(
            class = "red-text text-lighten-1",
            href = "#book",
            "BOOK NOW!"
          )
        )
      )
    )
  ),
  div(
    class = "row",
    div(
      class = "col s12 m4",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card",
        div(
          class = "card-image",
          tags$img(
            src = "img/barcelona.png"
          ),
          tags$span(
            class = "card-title",
            "Barcelona"
          )
        ),
        div(
          class = "card-content",
          tags$p(
            "John is in Barcelona between the 12/09/2017 and the 18/09/2017."
          )
        ),
        div(
          class = "card-action",
          tags$a(
            class = "red-text text-lighten-1",
            href = "#book",
            "BOOK NOW!"
          )
        )
      )
    ),
    div(
      class = "col s12 m4",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card",
        div(
          class = "card-image",
          tags$img(
            src = "img/toulouse.png"
          ),
          tags$span(
            class = "card-title",
            "Toulouse"
          )
        ),
        div(
          class = "card-content",
          tags$p(
            "John is in Toulouse between the 18/09/2017 and the 19/09/2017."
          )
        ),
        div(
          class = "card-action",
          tags$a(
            class = "red-text text-lighten-1",
            href = "#book",
            "BOOK NOW!"
          )
        )
      )
    ),
    div(
      class = "col s12 m4",
      div(
        `data-aos` = "fade-up",
        `data-aos-delay` = "100",
        `data-aos-duration` = "1500",
        class = "card",
        div(
          class = "card-image",
          tags$img(
            src = "img/paris.png"
          ),
          tags$span(
            class = "card-title",
            "Paris"
          )
        ),
        div(
          class = "card-content",
          tags$p(
            "John is in Marseile between the 19/09/2017 and the 20/09/2017."
          )
        ),
        div(
          class = "card-action",
          tags$a(
            class = "red-text text-lighten-1",
            href = "#book",
            "BOOK NOW!"
          )
        )
      )
    )
  )
)
```

```{r book}
div(
  class = "section scrollspy",
  id = "book",
  h2(
    class = "teal-text center",
    "MEET JOHN"
  ),
  p(
    class = "center",
    "Do not hesitate to suggest other locations, I may be able to accomodate.",
    br(),
    "Fill in the form below and I'll get back to you within 24 hours!"
  ),
  div(
    class = "row",
    tags$form(
      action = "https://formspree.io/jcoenep@gmail.com",
      method = "POST",
      class = "col s12",
      div(
        class = "row",
        div(
          class = "input-field col s6",
          tags$i(
            class = "material-icons prefix",
            "account_circle"
          ),
          tags$input(
            name="name",
            id = "icon_name",
            type = "text",
            class = "validate"
          ),
          tags$label(
            `for` = "icon_name",
            "Full Name"
          )
        ),
        div(
          class = "input-field col s6",
          tags$i(
            class = "material-icons prefix",
            "email"
          ),
          tags$input(
            name = "_replyto",
            id = "email",
            type = "text",
            class = "validate"
          ),
          tags$label(
            `for` = "emails",
            "Email"
          )
        )
      ),
      div(
        class = "row",
        div(
          class = "input-field col s6",
          tags$i(
            class = "material-icons prefix",
            "group_work"
          ),
          tags$input(
            name = "company",
            id = "icon_company",
            type = "text",
            class = "validate"
          ),
          tags$label(
            `for` = "icon_company",
            "Company"
          )
        ),
        div(
          class = "input-field col s6",
          tags$i(
            class = "material-icons prefix",
            "location_on"
          ),
          tags$input(
            name = "location",
            id = "icon_location",
            type = "text",
            class = "validate"
          ),
          tags$label(
            `for` = "icon_location",
            "Location"
          )
        )
      ),
      div(
        class = "row",
        div(
          class = "input-field col s12",
          tags$i(
            class = "material-icons prefix",
            "edit"
          ),
          tags$input(
            name="message",
            id = "icon_message",
            type = "text",
            class = "validate"
          ),
          tags$label(
            `for` = "icon_message",
            "Dates and message"
          )
        )
      ),
      tags$input(
        class = "btn btn-large teal center",
        type = "submit",
        value = "send"
      )
    )
  )
)
```

</div>
</main>
